services:
  backend:
    build: ./backend
    container_name: fastAPI
    ports:
      - "8000:7860" 
    volumes:
      - ./backend:/app
      - ./ai_vs_real_84k_train_data:/app/data
    env_file:
      - ./backend/.env
    environment:
      - PORT=7860
      - FRONTEND_URL=http://localhost:3000
    shm_size: '2gb'
    
    command: uvicorn main:app --host 0.0.0.0 --port 7860 --reload --reload-dir /app

  frontend:
    build: ./frontend
    container_name: reactApp
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend